'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Detalle_venta
    Public Property Id_detalle As Integer
    Public Property cantidad As Integer
    Public Property precio As Decimal
    Public Property nro_factura As Integer
    Public Property id_producto As Integer

    Public Overridable Property Producto As Producto
    Public Overridable Property Factura As Factura

End Class
