'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Factura
    Public Property nro_factura As Integer
    Public Property total As Decimal
    Public Property fecha_venta As Date
    Public Property id_cliente As Integer
    Public Property id_empleado As Integer

    Public Overridable Property Cliente As Cliente
    Public Overridable Property Detalle_venta As ICollection(Of Detalle_venta) = New HashSet(Of Detalle_venta)
    Public Overridable Property Empleado As Empleado

End Class
